version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testDb
    ports:
      - 5433:5432
    volumes:
      - ./postgres_db_data:/var/lib/postgresql/data
